npm install --save-dev gulp
npm install --save-dev  gulp-browserify
npm install --save-dev  gulp-coffee
npm install --save-dev  gulp-compass
npm install --save-dev  gulp-concat
npm install --save-dev  gulp-csslint
npm install --save-dev  gulp-cssnano
npm install --save-dev  gulp-if
npm install --save-dev  gulp-image-resize
npm install --save-dev  gulp-imagemin
npm install --save-dev  gulp-jshint
npm install --save-dev  gulp-jshint-html-reporter
npm install --save-dev  gulp-jsonminify
npm install --save-dev  gulp-minify-html
npm install --save-dev  gulp-plumber
npm install --save-dev  gulp-rename
npm install --save-dev  gulp-responsive
npm install --save-dev  gulp-sourcemaps
npm install --save-dev  gulp-uglify
npm install --save-dev  gulp-uncss
npm install --save-dev  gulp-util
npm install --save-dev  imagemin-pngcrush
npm install --save-dev  jquery
npm install --save-dev  jshint-stylish
npm install --save-dev  mustache
npm install --save-dev  run-sequence
npm install --save-dev  sharp
